apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: db2u-operator
  namespace: openshift-operators
spec:
  channel: v110508.0
  installPlanApproval: Automatic
  name: db2u-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
