apiVersion: db2u.databases.ibm.com/v1
kind: Db2uCluster
metadata:
  labels:
    cpd_db2: db2oltp
    db2u/cpdbr: db2u
  name: db2oltp-cognos
  namespace: cp4d
spec:
  size: 1
  license:
    accept: true
  environment:
    database:
      name: BLUDB
      settings:
        dftPageSize: '16384'
      ssl:
        certLabel: CN=zen-ca-cert
        secretName: db2oltp-internal-tls
    dbType: db2oltp
#    instance:
#      dbmConfig:
#        SRVCON_PW_PLUGIN: IBMIAMauthpwfile
#        group_plugin: IBMIAMauthgroup
#        srvcon_auth: GSS_SERVER_ENCRYPT
#        srvcon_gssplugin_list: IBMIAMauth
#      password: x-P_I-6W8b90%iRw
#      registry:
#        DB2AUTH: 'OSAUTHDB,ALLOW_LOCAL_FALLBACK,PLUGIN_AUTO_RELOAD'
#        DB2_FMP_RUN_AS_CONNECTED_USER: 'NO'
  advOpts:
    db2SecurityPlugin: cloud_gss_plugin
  version: 11.5.8.0-cn2
  storage: [] # PATCHED_BY_KUSTOMIZE
  volumeSources:
    - visibility:
        - db2u
      volumeSource:
        secret:
          secretName: zen-service-broker-secret

