apiVersion: db2u.databases.ibm.com/v1
kind: Db2uInstance
metadata:
  name: db2uinstance-cognos
  labels:
    app.kubernetes.io/instance: db2u-operator
    app.kubernetes.io/name: db2u-operator
    app.kubernetes.io/managed-by: Db2U-Team
spec:
  license:
    accept: true
  account:
    securityConfig:
      privilegedSysctlInit: true
  environment:
    partitionConfig:
      volumePerPartition: true
      total: 2
    databases:
      - name: BLUDB
    dbType: db2oltp
    disableNodePortService: true
  storage: {} # PATCHED_BY_KUSTOMIZE
  nodes: 1
  version: s11.5.8.0-cn2
