apiVersion: batch/v1
kind: Job
metadata:
  name: db2-cognos-init
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  selector: {}
  template:
    metadata:
      name: db2-cognos-init
    spec:
      serviceAccount: sa-job-db2-cognos-init
      containers:
        - name: call-db2
          image: quay.io/openshift/origin-cli:latest
          command: ["oc"]
          env:
            - name: DB2PASSWORD
              valueFrom:
                secretKeyRef:
                  name: c-db2oltp-cognos-instancepassword
                  key: password
          args:
            - exec
            - '-i'
            - c-db2oltp-cognos-db2u-0
            - '-c'
            - db2u
            - '--'
            - bash
            - '-c'
            - |
              cd /mnt/blumeta0/home/db2inst1/sqllib
              . ./db2profile   

              db2 CONNECT to BLUDB user db2inst1 using $DB2PASSWORD
              db2 UPDATE DATABASE CONFIGURATION USING APPLHEAPSZ 1024 DEFERRED; 
              db2 UPDATE DATABASE CONFIGURATION USING LOCKTIMEOUT 240 DEFERRED;
              db2 CREATE BUFFERPOOL CMDB_08KBP IMMEDIATE SIZE 1000 PAGESIZE 8K;
              db2 CREATE BUFFERPOOL CMDB_32KBP IMMEDIATE SIZE 1000 PAGESIZE 32K;
              db2 CREATE SYSTEM TEMPORARY TABLESPACE TSN_SYS_CMDB IN DATABASE PARTITION GROUP IBMTEMPGROUP PAGESIZE 32K BUFFERPOOL CMDB_32KBP;
              db2 CREATE USER TEMPORARY TABLESPACE TSN_USR_CMDB IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 8K BUFFERPOOL CMDB_08KBP;
              db2 CREATE REGULAR TABLESPACE TSN_REG_CMDB IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 8K BUFFERPOOL CMDB_08KBP; 
              db2 CREATE SCHEMA db2COGNOS AUTHORIZATION db2inst1;
              db2 ALTER BUFFERPOOL ibmdefaultbp size 49800;
      restartPolicy: Never
