apiVersion: batch/v1
kind: Job
metadata:
  name: db2-cognos-create-secret
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  selector: {}
  template:
    metadata:
      name: db2-cognos-create-secret
    spec:
      serviceAccount: sa-job-db2-cognos-init
      containers:
        - name: call-zen
          image: quay.io/openshift/origin-cli:latest
          command: ["bash"]
          env:
            - name: DB2PASSWORD
              valueFrom:
                secretKeyRef:
                  name: c-db2oltp-cognos-instancepassword
                  key: password
            - name: CP4DPASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-user-details
                  key: initial_admin_password
          args:
            - '-c'
            - |
              set -x
              TOKEN=$(curl -k --request POST \
                --url https://internal-nginx-svc.cp4d.svc:12443/icp4d-api/v1/authorize \
                --header 'content-type: application/json' \
                --data '{"username":"admin","password":"'"$CP4DPASSWORD"'"}' | python3 -c "import sys, json; print(json.load(sys.stdin)['token'])")

              curl -k -X POST \
                https://internal-nginx-svc.cp4d.svc:12443/zen-data/v2/secrets \
                -H 'Authorization: Bearer '"$TOKEN" \
                -H 'Content-Type: application/json' \
              -d '{
                  "secret_name": "db2-cognos-credentials",
                  "description": "Login credentials to the DB2 used for Cognos Analytics",
                  "secret": {
                      "credentials": {
                          "username": "db2inst1",
                          "password": "'"$DB2PASSWORD"'"
                      }
                  },    
                  "type": "credentials",
                  "vault_urn": "0000000000:internal"
              }'
      restartPolicy: Never
