kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-job-db2-cognos-init
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ""
    resources:
      - pods
  - verbs:
      - create
    apiGroups:
      - ""
    resources:
      - pods/exec
