apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- job-roks-db2-root-no-squash.yaml
- rb-roks-db2-root-no-squash.yaml
- role-roks-db2-root-no-squash.yaml
- sa-roks-db2-root-no-squash.yaml

patchesStrategicMerge:
- storage.yaml
