kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-roks-db2-root-no-squash.yaml
subjects:
  - kind: ServiceAccount
    name: account-cp4d-db2uinstance-cognos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-roks-db2-root-no-squash
