kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-roks-db2-root-no-squash
subjects:
  - kind: ServiceAccount
    name: sa-roks-db2-root-no-squash
    namespace: cp4d
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-roks-db2-root-no-squash
