kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-roks-db2-root-no-squash
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ""
    resources:
      - nodes
  - verbs:
      - get
      - list
      - create
      - watch
    apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - pods/log
  - verbs:
      - use 
    apiGroups:
      - security.openshift.io
    resourceNames:
      - hostaccess
    resources:
      - securitycontextconstraints

