kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-roks-db2-root-no-squash
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ""
    resources:
      - nodes
  - verbs:
      - get
      - list
      - create
    apiGroups:
      - ""
    resources:
      - namespaces
