kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - serviceaccounts
  - verbs:
      - '*'
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - '*'
    apiGroups:
      - cpd.ibm.com
    resources:
      - ibmcpds
  - verbs:
      - '*'
    apiGroups:
     - ca.cpd.ibm.com
    resources:
      - caservices
  - verbs:
      - '*'
    apiGroups:
      - db2u.databases.ibm.com
    resources:
      - db2uclusters
  - verbs:
      - '*'
    apiGroups:
      - databases.cpd.ibm.com
    resources:
      - db2oltpservices
