kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - cpd.ibm.com
      - ca.cpd.ibm.com
    resources:
      - ibmcpds
      - caservices
