apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4d-control-plane
  namespace: openshift-gitops
  labels:
    group: applications
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  destination:
    namespace: cp4i
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./envs/ibm-classic/control-plane
    targetRevision: 'HEAD'
    repoURL: https://github.com/thomas-mattsson/cognos-cp4d-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
